import pytest
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))
from validate_metadata import extract_headings, generate_index_table, inject_index


SAMPLE = """---
title: Test
version: 1.0.0
updated: 2026-02-24
scope: test
category: ssot
subcategory: test
domain: [test]
---

<!-- INDEX: auto-generated by validate_metadata.py — do not edit manually -->
| Section | Summary |
|---|---|
| old | old |
<!-- END INDEX -->

## Architecture
Handles the core routing logic for all requests.

## Hook Wiring
Three hooks fire on session events.

## Installer
Single-purpose script, idempotent.
"""


def test_extract_headings():
    headings = extract_headings(SAMPLE)
    assert headings == [
        ("Architecture", "Handles the core routing logic for all requests"),
        ("Hook Wiring", "Three hooks fire on session events"),
        ("Installer", "Single-purpose script, idempotent"),
    ]


def test_generate_index_table():
    headings = [("Architecture", "Core routing."), ("Installer", "Idempotent.")]
    table = generate_index_table(headings)
    assert "| [Architecture](#architecture) |" in table
    assert "Core routing." in table
    assert "| [Installer](#installer) |" in table


def test_inject_index_replaces_existing():
    new_table = "| Section | Summary |\n|---|---|\n| [Architecture](#architecture) | Core. |\n"
    result = inject_index(SAMPLE, new_table)
    assert "| old | old |" not in result
    assert "| [Architecture](#architecture) | Core. |" in result


def test_inject_index_adds_when_missing():
    content = "---\ntitle: T\n---\n\n## Foo\nBar baz.\n"
    new_table = "| Section | Summary |\n|---|---|\n| [Foo](#foo) | Bar baz. |\n"
    result = inject_index(content, new_table)
    assert "<!-- INDEX:" in result
    assert "| [Foo](#foo) | Bar baz. |" in result
